// <auto-generated />
using System;
using CalorieTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502112128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("CalorieTracker.Models.DailyGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsTargetG")
                        .HasColumnType("REAL");

                    b.Property<double>("FatTargetG")
                        .HasColumnType("REAL");

                    b.Property<double>("FiberTargetG")
                        .HasColumnType("REAL");

                    b.Property<double>("ProteinTargetG")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DailyGoals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalorieTarget = 2000.0,
                            CarbsTargetG = 250.0,
                            FatTargetG = 65.0,
                            FiberTargetG = 30.0,
                            ProteinTargetG = 150.0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CalorieTracker.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CalciumMg")
                        .HasColumnType("REAL");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsG")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("FatG")
                        .HasColumnType("REAL");

                    b.Property<double>("FiberG")
                        .HasColumnType("REAL");

                    b.Property<string>("FoodBarcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("IronMg")
                        .HasColumnType("REAL");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinG")
                        .HasColumnType("REAL");

                    b.Property<double>("QuantityGrams")
                        .HasColumnType("REAL");

                    b.Property<double?>("SodiumMg")
                        .HasColumnType("REAL");

                    b.Property<double>("SugarG")
                        .HasColumnType("REAL");

                    b.Property<double?>("VitaminAMcg")
                        .HasColumnType("REAL");

                    b.Property<double?>("VitaminCMg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
